---
- name: Testing of Playbook
  hosts: app
  become: true

  tasks:
    - name: apt install
      yum:
        name : "{{ item }}"
        state: present
      with_items:
        - httpd
    - name: debug
      debug:
        msg: "testing {{ item }}"
      with_items:
        - httpd
