---
- name: Testing of Playbook
  hosts: app
  become: true

  vars:
    files:
      - testing1.txt
      - testing2.txt
      - testing3.txt

  tasks:
    - name: apt install
      yum:
        name : "{{ item }}"
        state: present
      with_items:
        - httpd
  
    - name: copy files
      copy:
        src: "{{ item }}"
        dest: "/home/vagrant/{{ item }}"
        mode: '0644'
      with_items: "{{ files }}"

    - name: copy files
      lineinfile:
        path: "/home/vagrant/{{ item }}"
        line: "This is second line"
        state: present
      with_items: "{{ files }}"

    - name: Remove file (delete file)
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ files }}"
