---
- name: Testing of Playbook
  hosts: app
  become: true

  vars:
    files:
      - testing1.txt
      - testing2.txt
      - testing3.txt

  tasks:
    - name: apt install
      yum:
        name : "{{ item }}"
        state: present
      with_items:
        - httpd
    - name: copy files
      copy:
        src: "{{ item }}"
        dest: "/home/vagrant/{{ item }}"
        mode: '0644'
      with_items: "{{ files }}"

