---
- name: Assert
  hosts: app
  become: true
  vars:
    color: "REd"
  tasks:
    - name: assert Value
      assert:
        that: color is local.colors.color
        fail_msg: "'color' is not red"
        success_msg: "'color' is red"
      ignore_errors: true
        