---
- name: Pre Test
  hosts: app
  become: true
  handlers:
  - name: notify_task
    file:
      path: /home/vagrant/notify_user
      state: directory
  pre_tasks:
  - name: Create folder
    file:
      path: /home/vagrant/pre_tasks
      state: directory
  tasks:
    - name: Download Url
      get_url: 
        url: https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2021-financial-year-provisional/Download-data/annual-enterprise-survey-2021-financial-year-provisional-csv.csv
        dest: /home/vagrant/file.csv
      notify: notify_task
  post_tasks:
    - name: Create folder
      file:
        path: /home/vagrant/post_tasks
        state: directory