---
- name: This is simple yaml
  hosts: app
  tasks:
    - name: Who Am I
      ansible.builtin.command: whoami
- name: This is second yaml
  ignore_errors: true
  hosts: app
  tasks:
    - name: Testing module command
      ansible.builtin.ping:
      changed_when: false
